### ISSUE TITLE
EventHandler doesn't support class inference for custom abstract `Event` classes

### ISSUE THREAD

**Issue by Katakurinna** [xXNurioXx/ReflectedEventHandler#22]
I've tried to make a `BaseEvent` extending `Event` to make children objects, but **REH** does not allow me to do it. 
It does not recognize the `BaseEvent` has a valid `Event`.

Example code:
```java
public class BaseEvent extends Event { }
```
```java
public class ChildEvent extends BaseEvent { }
```
Currently, **REH** does not accept ChildEvent as a valid event.

**Comment by xXNurioXx** [comment]
This issue has been fixed at the #23 pull request! 🎉
