### ISSUE TITLE
upgrade junit4 to junit5

### ISSUE THREAD

**Issue by qigao** [xXNurioXx/ReflectedEventHandler#31]
Hi @xXNurioXx ,

 just create a PR for upgrading junit4 to junit5.
as it's my first PR on github, i may falsely changed the code structure, 
like moved annotation and abstract things to a new package.
sorry for the inconvenience, it's not my intension to change it without your permission.

**Comment by xXNurioXx** [comment]
Hi @qigao, I will review your PR and apply some changes if needed this afternoon.

Thanks for your contribution!
